### Get hello world
GET http://localhost:3001
Content-Type: application/json

### Test password
POST http://localhost:3001/validate-password
Content-Type: application/json

{
    "password": "12344666"
}

### User Update
PUT http://localhost:3001/update-user
Content-Type: application/json

{
    "password": "12344666"
}

### User Update PATCH
PATCH http://localhost:3001/update-user
Content-Type: application/json

{
    "password": "12344666"
}