### Get hello world
GET http://localhost:3001
Content-Type: application/json

### Test password
POST http://localhost:3001/validate-password
Content-Type: application/json

{
    "password": "12344666"
}


### Users
GET http://localhost:3001/users



### Delete Users
DELETE http://localhost:3001/users/2

